export interface Theme {
  id: string
  name: string
  colors: Record<string, string>
}

export const themes: Theme[] = [
  {
    id: 'dark',
    name: 'Dark',
    colors: {
      '--color-bg': '#0a0a0f',
      '--color-bg-secondary': '#12121a',
      '--color-bg-tertiary': '#1a1a25',
      '--color-bg-hover': '#22222f',
      '--color-bg-active': '#2a2a3a',
      '--color-surface': '#16161f',
      '--color-surface-hover': '#1e1e2a',
      '--color-border': '#2a2a3a',
      '--color-border-light': '#33334a',
      '--color-text': '#e8e8f0',
      '--color-text-secondary': '#9090a8',
      '--color-text-muted': '#606078',
      '--color-accent': '#6366f1',
      '--color-accent-hover': '#7577f5',
      '--color-accent-muted': '#6366f120',
      '--color-success': '#22c55e',
      '--color-warning': '#f59e0b',
      '--color-danger': '#ef4444',
      '--color-info': '#3b82f6',
    },
  },
  {
    id: 'light',
    name: 'Light',
    colors: {
      '--color-bg': '#f8f9fa',
      '--color-bg-secondary': '#ffffff',
      '--color-bg-tertiary': '#f0f1f3',
      '--color-bg-hover': '#e9eaed',
      '--color-bg-active': '#dddee2',
      '--color-surface': '#ffffff',
      '--color-surface-hover': '#f5f5f7',
      '--color-border': '#d1d5db',
      '--color-border-light': '#e5e7eb',
      '--color-text': '#1f2937',
      '--color-text-secondary': '#6b7280',
      '--color-text-muted': '#9ca3af',
      '--color-accent': '#6366f1',
      '--color-accent-hover': '#4f46e5',
      '--color-accent-muted': '#6366f120',
      '--color-success': '#16a34a',
      '--color-warning': '#d97706',
      '--color-danger': '#dc2626',
      '--color-info': '#2563eb',
    },
  },
  {
    id: 'nord',
    name: 'Nord',
    colors: {
      '--color-bg': '#2e3440',
      '--color-bg-secondary': '#3b4252',
      '--color-bg-tertiary': '#434c5e',
      '--color-bg-hover': '#4c566a',
      '--color-bg-active': '#556078',
      '--color-surface': '#3b4252',
      '--color-surface-hover': '#434c5e',
      '--color-border': '#4c566a',
      '--color-border-light': '#556078',
      '--color-text': '#eceff4',
      '--color-text-secondary': '#d8dee9',
      '--color-text-muted': '#7b88a1',
      '--color-accent': '#88c0d0',
      '--color-accent-hover': '#8fbcbb',
      '--color-accent-muted': '#88c0d020',
      '--color-success': '#a3be8c',
      '--color-warning': '#ebcb8b',
      '--color-danger': '#bf616a',
      '--color-info': '#81a1c1',
    },
  },
  {
    id: 'catppuccin-mocha',
    name: 'Catppuccin Mocha',
    colors: {
      '--color-bg': '#1e1e2e',
      '--color-bg-secondary': '#181825',
      '--color-bg-tertiary': '#313244',
      '--color-bg-hover': '#45475a',
      '--color-bg-active': '#585b70',
      '--color-surface': '#181825',
      '--color-surface-hover': '#313244',
      '--color-border': '#45475a',
      '--color-border-light': '#585b70',
      '--color-text': '#cdd6f4',
      '--color-text-secondary': '#a6adc8',
      '--color-text-muted': '#6c7086',
      '--color-accent': '#cba6f7',
      '--color-accent-hover': '#b4befe',
      '--color-accent-muted': '#cba6f720',
      '--color-success': '#a6e3a1',
      '--color-warning': '#f9e2af',
      '--color-danger': '#f38ba8',
      '--color-info': '#89b4fa',
    },
  },
]
