export interface Theme {
  id: string
  name: string
  colors: Record<string, string>
  isCustom?: boolean
}

/** Human-readable labels for each color variable */
export const colorLabels: Record<string, string> = {
  '--color-bg': 'Background',
  '--color-bg-secondary': 'Secondary Background',
  '--color-bg-tertiary': 'Tertiary Background',
  '--color-bg-hover': 'Hover Background',
  '--color-bg-active': 'Active Background',
  '--color-surface': 'Surface',
  '--color-surface-hover': 'Surface Hover',
  '--color-border': 'Border',
  '--color-border-light': 'Border Light',
  '--color-text': 'Text',
  '--color-text-secondary': 'Secondary Text',
  '--color-text-muted': 'Muted Text',
  '--color-accent': 'Accent',
  '--color-accent-hover': 'Accent Hover',
  '--color-accent-muted': 'Accent Muted',
  '--color-success': 'Success',
  '--color-warning': 'Warning',
  '--color-danger': 'Danger',
  '--color-info': 'Info',
}

/** Group color variables for the editor UI */
export const colorGroups = {
  'Backgrounds': ['--color-bg', '--color-bg-secondary', '--color-bg-tertiary', '--color-bg-hover', '--color-bg-active', '--color-surface', '--color-surface-hover'],
  'Borders': ['--color-border', '--color-border-light'],
  'Text': ['--color-text', '--color-text-secondary', '--color-text-muted'],
  'Accent': ['--color-accent', '--color-accent-hover', '--color-accent-muted'],
  'Status': ['--color-success', '--color-warning', '--color-danger', '--color-info'],
}

export const builtinThemes: Theme[] = [
  {
    id: 'notion-light',
    name: 'Notion Light',
    colors: {
      '--color-bg': '#ffffff',
      '--color-bg-secondary': '#f7f6f3',
      '--color-bg-tertiary': '#f0efec',
      '--color-bg-hover': '#e8e7e4',
      '--color-bg-active': '#dddcda',
      '--color-surface': '#ffffff',
      '--color-surface-hover': '#f7f6f3',
      '--color-border': '#e3e2df',
      '--color-border-light': '#ebebea',
      '--color-text': '#37352f',
      '--color-text-secondary': '#6b6b6b',
      '--color-text-muted': '#9b9a97',
      '--color-accent': '#2eaadc',
      '--color-accent-hover': '#1a9dc7',
      '--color-accent-muted': '#2eaadc18',
      '--color-success': '#0f7b6c',
      '--color-warning': '#d9730d',
      '--color-danger': '#e03e3e',
      '--color-info': '#2eaadc',
    },
  },
  {
    id: 'notion-dark',
    name: 'Notion Dark',
    colors: {
      '--color-bg': '#191919',
      '--color-bg-secondary': '#202020',
      '--color-bg-tertiary': '#2a2a2a',
      '--color-bg-hover': '#333333',
      '--color-bg-active': '#3c3c3c',
      '--color-surface': '#252525',
      '--color-surface-hover': '#2e2e2e',
      '--color-border': '#383838',
      '--color-border-light': '#444444',
      '--color-text': '#e3e3e1',
      '--color-text-secondary': '#9b9a97',
      '--color-text-muted': '#6b6b6b',
      '--color-accent': '#529cca',
      '--color-accent-hover': '#4a8ab5',
      '--color-accent-muted': '#529cca18',
      '--color-success': '#4dab9a',
      '--color-warning': '#d9730d',
      '--color-danger': '#e03e3e',
      '--color-info': '#529cca',
    },
  },
  {
    id: 'parchment',
    name: 'Parchment',
    colors: {
      '--color-bg': '#f5f0e8',
      '--color-bg-secondary': '#ece6d9',
      '--color-bg-tertiary': '#e3dccf',
      '--color-bg-hover': '#dbd3c4',
      '--color-bg-active': '#d0c7b6',
      '--color-surface': '#faf6ef',
      '--color-surface-hover': '#f0ebe1',
      '--color-border': '#d0c7b6',
      '--color-border-light': '#ddd5c6',
      '--color-text': '#3d3429',
      '--color-text-secondary': '#6b5f50',
      '--color-text-muted': '#9c8e7c',
      '--color-accent': '#8b6f4e',
      '--color-accent-hover': '#7a6043',
      '--color-accent-muted': '#8b6f4e18',
      '--color-success': '#5a7c5a',
      '--color-warning': '#b8860b',
      '--color-danger': '#a0522d',
      '--color-info': '#5b7fa5',
    },
  },
  {
    id: 'ink',
    name: 'Ink',
    colors: {
      '--color-bg': '#1a1a1e',
      '--color-bg-secondary': '#222226',
      '--color-bg-tertiary': '#2a2a2f',
      '--color-bg-hover': '#333338',
      '--color-bg-active': '#3c3c42',
      '--color-surface': '#242428',
      '--color-surface-hover': '#2c2c31',
      '--color-border': '#3c3c42',
      '--color-border-light': '#48484f',
      '--color-text': '#d4d2cc',
      '--color-text-secondary': '#9e9b93',
      '--color-text-muted': '#6e6b64',
      '--color-accent': '#a09080',
      '--color-accent-hover': '#b0a090',
      '--color-accent-muted': '#a0908018',
      '--color-success': '#7a9a6d',
      '--color-warning': '#c4a35a',
      '--color-danger': '#c47a6a',
      '--color-info': '#7a9ab0',
    },
  },
  {
    id: 'moss',
    name: 'Moss',
    colors: {
      '--color-bg': '#1c201c',
      '--color-bg-secondary': '#232823',
      '--color-bg-tertiary': '#2b312b',
      '--color-bg-hover': '#353b35',
      '--color-bg-active': '#3f463f',
      '--color-surface': '#262b26',
      '--color-surface-hover': '#2e342e',
      '--color-border': '#3f463f',
      '--color-border-light': '#4b534b',
      '--color-text': '#d0d4c8',
      '--color-text-secondary': '#98a08e',
      '--color-text-muted': '#6b7360',
      '--color-accent': '#7a9468',
      '--color-accent-hover': '#8aa87a',
      '--color-accent-muted': '#7a946818',
      '--color-success': '#6b9a5a',
      '--color-warning': '#b8a050',
      '--color-danger': '#b87060',
      '--color-info': '#6a8a9e',
    },
  },
  {
    id: 'dusk',
    name: 'Dusk',
    colors: {
      '--color-bg': '#1e1a22',
      '--color-bg-secondary': '#26222a',
      '--color-bg-tertiary': '#2e2a33',
      '--color-bg-hover': '#38343e',
      '--color-bg-active': '#423e48',
      '--color-surface': '#28242c',
      '--color-surface-hover': '#302c35',
      '--color-border': '#423e48',
      '--color-border-light': '#4e4a55',
      '--color-text': '#d4d0d8',
      '--color-text-secondary': '#9e98a5',
      '--color-text-muted': '#6e6875',
      '--color-accent': '#9a7eb0',
      '--color-accent-hover': '#aa8ec0',
      '--color-accent-muted': '#9a7eb018',
      '--color-success': '#7a9a6d',
      '--color-warning': '#c4a35a',
      '--color-danger': '#c47a7a',
      '--color-info': '#7a8ec0',
    },
  },
  {
    id: 'ocean',
    name: 'Ocean',
    colors: {
      '--color-bg': '#0f1923',
      '--color-bg-secondary': '#162230',
      '--color-bg-tertiary': '#1d2b3c',
      '--color-bg-hover': '#263648',
      '--color-bg-active': '#2f4054',
      '--color-surface': '#192a3a',
      '--color-surface-hover': '#213344',
      '--color-border': '#2f4054',
      '--color-border-light': '#3a4d62',
      '--color-text': '#c8d6e5',
      '--color-text-secondary': '#8fa4b8',
      '--color-text-muted': '#5a7a94',
      '--color-accent': '#48b1bf',
      '--color-accent-hover': '#5bc4d2',
      '--color-accent-muted': '#48b1bf18',
      '--color-success': '#66d9a0',
      '--color-warning': '#f0b429',
      '--color-danger': '#e66767',
      '--color-info': '#48b1bf',
    },
  },
  {
    id: 'rose',
    name: 'Rose',
    colors: {
      '--color-bg': '#fdf2f8',
      '--color-bg-secondary': '#fce7f3',
      '--color-bg-tertiary': '#fbcfe8',
      '--color-bg-hover': '#f9a8d4',
      '--color-bg-active': '#f472b6',
      '--color-surface': '#fdf2f8',
      '--color-surface-hover': '#fce7f3',
      '--color-border': '#f9a8d4',
      '--color-border-light': '#fbcfe8',
      '--color-text': '#4a1942',
      '--color-text-secondary': '#831843',
      '--color-text-muted': '#be185d',
      '--color-accent': '#db2777',
      '--color-accent-hover': '#be185d',
      '--color-accent-muted': '#db277718',
      '--color-success': '#059669',
      '--color-warning': '#d97706',
      '--color-danger': '#dc2626',
      '--color-info': '#2563eb',
    },
  },
]

/** For backward compat */
export const themes = builtinThemes
